### ISSUE TITLE
Design Proposal: Preview Deployment

### ISSUE THREAD

**Issue by koudaiii** [Azure/aca-review-apps#27]
## Preview Deployment

- [Summary](#summary)
- [Motivation](#motivation)
  - [Goals](#goals)
  - [Non-Goals](#non-goals)
- [Proposal](#proposal)
  - [User Stories](#user-stories)
- [Design Details](#design-details)

## Summary

Improve Developer experience. This proposal makes a dedicated environment, deploy, and a custom URL dispatch per Pull Request. ref https://vercel.com/docs/concepts/git/vercel-for-github
![image](https://user-images.githubusercontent.com/2929102/189617422-056cdf4a-6f28-46d7-b7cb-f4c6c5025b34.png)

## Motivation

More and more environments are building with Cloud Native on cloud services. As a result, developers need to leverage cloud services to check and develop. However, setting up cloud services is time-consuming for teams to review and demo.

### Goals

- You can confirm with only one click
- We can check it under conditions similar to those of production.
- Your teams can share and demonstrate.
- and secure

### Non-Goals

- For public OSS (This proposal is for internal development)
- Provisioning (Infrastructure as Code)
  - To create a revision for an existing container app
- for production(without `main` branch)
- Reinventing the wheel for already existing GitHub actions

## Proposal

A developer creates a branch, writes code, and sends a pull request. At that time, this GitHub Action creates a dedicated environment similar to the production environment. And, It makes a custom URL. Then, it notifies on GitHub. We can confirm the browser. When this pull request is closed, it will delete the environment.(Optional)

- ex: Vercel

<img width="771" alt="image" src="https://user-images.githubusercontent.com/2929102/189575457-128e2a82-4b06-4412-9ea4-4868fc64c170.png">

- ex: heroku review app

https://devcenter.heroku.com/articles/github-integration-review-apps

![image](https://user-images.githubusercontent.com/2929102/190069161-8a1d6982-7a52-40bd-aae3-3383a9b0d5aa.png)

### User Stories

Some teams can demonstrate as a PoC per Pull Request.

### [WIP] Prepare Azure Container App

TBD

### [WIP] Set up GitHub Action

- `.github/workflows/preview-deploy.yml`

```YAML
on:
  push:
  pull_request:
    types: [opened, synchronize, closed]

name: Preview Deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: # TODO
      CONTAINER_APP_NAME: # TODO
      AZURE_CONTAINER_REGISTRY: # TODO
      DOCKER_IMAGE_NAME: ${{ env.AZURE_CONTAINER_REGISTRY }}:${{ github.sha }} #TODO

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      if: github.event.action != 'closed'
      uses: docker/setup-buildx-action@v1

    - name: Log in to container registry
      if: github.event.action != 'closed'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

    - name: Build and push container image to registry
      if: github.event.action != 'closed'
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:
        file: ./Dockerfile
        context: ./

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    steps:
    - name: 'Deploy to Azure Container Apps'
      if: github.event.action != 'closed'
      uses: azure/aca-preview@v0.0.1
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        name: ${{ env.CONTAINER_APP_NAME }}
        image: ${{ env.DOCKER_IMAGE_NAME }}
        revision-name-suffix: ${{ github.sha }}

    - name: Deactivate Preview Deployment
        if: github.event.action == 'closed'
        uses: azure/aca-preview@v0.0.1
        with:
          deactivate-revision-mode: true
          resource-group: ${{ env.RESOURCE_GROUP }}
          name: ${{ env.CONTAINER_APP_NAME }}
          image: ${{ env.DOCKER_IMAGE_NAME }}
          revision-name-suffix: ${{ github.event.pull_request.head.sha }}

```

### Create a pull request

- This aca-preview creates a new revision from an existing container app.
- Since revisions cannot be updated, it is necessary to create a new revision when a commit is repeated on a pull request.

if possible, In order to have one revision per pull request, it is necessary to deactivate the existing revision when creating a new revision.

Just idea:  Can I label a pull request and swap the label with the latest revision when a commit or push comes in? And can I invalidate existing revisions?

### Merge to `main`

- Existing revisions are deactivated

## Todo 
- [x] Create base implementations @yuhattor 
- [x] Fix this design proposal @koudaiii #27
  - [x] Define URL rule(Update after push so that the latest is always visible per pull request. What URLs are issued per pull request?) #27
  - [x] Architecture View (Picture of how it works) @ry0y4n 
- [x] Documentation of how to setup(How to create an existing GitHub Action by creating a Container App using the az command) @yuhattor @ry0y4n  
- [x] Implement MVP(minimum viable product)
  - [x] sample application for demo (Create a demo environment that is easy to understand the usage for UI/UX verification.) @horihiro https://github.com/horihiro/aca-preview-sample-workflow
  - [x] Implement create new revision (Create a revision of weight:0) @ry0y4n #36 
  - [x] Implement the ability to notify on pull requests(Notify URL to Pull Request after revision is made) @horihiro #31 
- [ ] (Optional) Implement cleanup after merging(preview deployment lifecycle)
- [ ] (Optional) Implement custom registry(Specify registry for preview deployment)
- [ ] (Optional) Implement multi-container(Multiple container support)

**Comment by koudaiii** [comment]
## Revision v.s another azure container app

**Comment by ry0y4n** [comment]
```
on: [push, pull_request]
  
name: Container Deployment Sample Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: actions/setup-node@v2
      with:
        node-version: '16.13.0'
        registry-url: 'https://npm.pkg.github.com'
    - run: npm install 
    - run: tsc
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Deploy to Azure Container Apps'
      uses: ./
      with:
        resource-group: aca-sample-rg
        name: momosuke-container3
        location: 'East US'
        subscription-id: 'a4deccb1-a1f6-40cb-a923-f55a7d22c32d'
        managed-environment-name: 'momosuke-container-env'
        dapr-app-port: 3000
        dapr-app-protocol: 'http'
        dapr-enabled: true
        ingress-external: true
        ingress-target-port: 3000
        ingress-custom-domains-json: |
          [
          ]
        # ingress-custom-domains-json: |
        #   [
        #     {
        #       "name": "www.my-name.com", 
        #       "bindingType": "SniEnabled", 
        #       "certificateId": "/subscriptions/a4deccb1-a1f6-40cb-a923-f55a7d22c32d/resourceGroups/aca-sample-rg/providers/Microsoft.App/managedEnvironments/momosuke-container-env/certificates/527CAD9560BF6B5F95AE62E94BF7A7CA0EC5C294ACC77622A0CF24527936C63C"
        #     }
        #   ]
        # ingress-traffic-json: |
        #   [
        #   ]
        # ingress-traffic-json: |
        #   [ 
        #     { 
        #       "label": "production", 
        #       "revisionName": "yuhattor-container3--qpxyrnn", 
        #       "weight": 100 
        #     } 
        #   ]
        # scale-max-replicas: 5
        # scale-min-replicas: 1
        # scale-rules-json: |
        #   [
        #   ]
        scale-rules-json: |
          [
            {
              "name": "httpscalingrule",
              "custom": { 
                "type": "http", 
                "metadata": { 
                  "concurrentRequests": "30" 
                }
              }
            }
          ]
        containers-config-json: | 
          [
            {
              "name":"simple-hello-world-container",
              "image": "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest",
              "probes":[
                 {
                    "type":"Liveness",
                    "httpGet":{
                       "path":"/health",
                       "httpHeaders":[
                          {
                             "name":"Custom-Header",
                             "value":"Awesome"
                          }
                       ],
                       "port":8080
                    },
                    "initialDelaySeconds":3,
                    "periodSeconds":3
                 }
              ]
            }
          ]


```

**Comment by ry0y4n** [comment]
https://github.com/ry0y4n/aca-deploy/blob/main/.github/workflows/sample.yml

**Comment by yuhattor** [comment]
Here is a yaml file of the contents of containers.
https://docs.microsoft.com/en-us/rest/api/containerapps/container-apps/create-or-update?tabs=HTTP

Assuming that file names like this one as ```containers-config.yml``` will be written?

```yaml
- name: acatest1
  image: repo/acatest1:v1
  args: "foo bar"
  command: "foo bar"
  env: "foo1=bar1, foo2=bar2"
  volumeMounts:
  - storageName: "string"
    name: "string"
    storageType:
    - AzureFile: "string"
      EmptyDir: "string"
  resources: 
  - cpu: 0.5
    ephemeralStorage: "1Gi"
    memory: "250Mb"
  probes:
  - type: Liveness
    httpGet:
      path: "/health"
      httpHeaders:
      - name: Custom-Header
        value: Awesome
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
  - type: Liveness
    httpGet:
      path: "/health"
      httpHeaders:
      - name: Custom-Header
        value: Awesome
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
- name: acatest2
  image: repo/acatest2:v1
  probes:
  - type: Liveness
    httpGet:
      path: "/health"
      httpHeaders:
      - name: Custom-Header
        value: Awesome
      port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3

```

**Comment by koudaiii** [comment]
- [ ] revision handling
- [ ] ppt
- [ ] notification 
- [ ] sample app

**Comment by yuhattor** [comment]
Moved remain tasks to #65
